### ISSUE TITLE
Two data folders 🤔

### ISSUE THREAD

**Issue by F-said** [JacquelineGomez06/Cyber_Capstone#17]
**Problem**

There seems to be two data folders: "data" and "Data."

Let's decide which one to keep and which one to remove. This will most likely result in a git workflow issue due to [case sensitivity](https://stackoverflow.com/questions/27749219/working-in-git-with-directories-with-the-same-name-but-different-case-in-windows). 

**Expected Output**

One folder with all relevant data.

**Definition of done**

Everyone's GitHub repo's work; one data folder with all info; committed and merged

**Comment by JacquelineGomez06** [comment]
data folders merged, sticking with lower_case
