### ISSUE TITLE
Scatter Plot Replacement 

### ISSUE THREAD

**Issue by F-said** [JacquelineGomez06/Cyber_Capstone#18]
**Problem**

Scatter plots are usually reserved for two continuous variables that don't relate to time. What would be a better graph for this relationship?

![image](https://github.com/JacquelineGomez06/Cyber_Capstone/assets/26397102/1d3618c7-691c-4ff7-aa48-3fd4b9703cdc)

**Expected Output**

Think of what graphs we've used in the past to express relationships bound by time

**Definition of done**

- changes committed and merged
- new graph replaces old
- old graph removed

**Comment by TechMikeSol** [comment]
Updated but not yet pushed
